on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    container:
      image: hello:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v3
      - name: build image
        run: docker build -t hello ./
      - name: run container
        run: docker run --name hello -d -p 3000:3000 hello:latest