on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build image
        id: build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: hello
      - name: run container
        run: |
          docker run --name hello -d -p 3000:3000 ${{ steps.build.outputs.ImageID }}
      - run: docker ps; sleep 2
      - name: inspect container
        run: |
          curl -v --retry 5 --retry-max-time 30 http://localhost:3000