on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
      - name: run container
        run: |
          docker run \
            docker.io/library/latest
